### ISSUE TITLE
Test Results window showing incorrect results

### ISSUE THREAD

**Issue by dellgreen** [offa/NBCndUnit#4] opened 2015-11-14 22:52 UTC
I have a strange issue with a project i have just migrated from CppUnit to google test.
I have 160 unit tests but the test results window is saying 311 which is wrong, and showing the same test cases twice.
The output from google test is correct although I dont know enough about it to know what in the stdout may be causing the issue (I'm not streaming or printing anything myself to stdout).
Using Google test 1.7.0 in Netbeans 8.1 on Mac OS X 10.9.5
When I create a simple hello world new project the Tests results window shows the correct results.

I have attached google test stdout and screen grab of netbeans test window

![googletest-nbresultswindow](https://cloud.githubusercontent.com/assets/12861109/11166187/0978a206-8b22-11e5-9d51-fe824eb5070b.jpg)
[googletest-stdout.txt](https://github.com/offa/NBCndUnit/files/34763/googletest-stdout.txt)

**Comment by dellgreen** [comment] 2015-11-15 12:43
Interestingly the last test in the results window is not duplicated.

**Comment by offa** [comment] 2015-11-15 17:48
From a first look it seems to be caused by displaying the results if multiple test exe's are executed. The parser seems fine, but the result / report are generated - or shown - multiple times. The other frameworks are affected by this too.

Thanks for reporting, i'll have a closer look to this.

**Comment by offa** [comment] 2015-11-15 17:50
Btw. i was able to reproduce this by creating more than one _Test Folder_ (= Test exe) incl. Testmain and some testcases.

**Comment by dellgreen** [comment] 2015-11-15 20:40
Ok great, glad it wasn't me be silly. I do have many test folders in the Test Files Folder as I couldn't figure out how else to be able to run individual tests in isolation from other tests when debugging the tests, although now this has given me the problem of how to have a test superclass that all tests inherit from as most of my tests run the same tests but with different parameters.

**Comment by offa** [comment] 2015-11-16 20:59
@dellgreen If you have some time for testing, i have pushed `dev/issue4` -- or you can download compiled version here: http://www91.zippyshare.com/v/6FxAuEir/file.html

Please note, this gtest / gmock only so far.

Sha256:

```
822dd0ee6665aedbbc43b5ff73b7a56af449208c95727ecefb84bf1168d59fe6  NBCndUnit-0.7.0-SNAPSHOT.nbm
```

**Comment by dellgreen** [comment] 2015-11-17 10:57
I have tested the compiled version and it is all now working correctly, thank you :)

**Comment by offa** [comment] 2015-11-17 20:17
Thanks for confirming; i'll close this issue then.

Though, i have to fix the other two frameworks too -- and there the things are a bit more tricky ...

**Closed as completed by offa** 2015-11-17 20:17 UTC
Labels: bug
