### ISSUE TITLE
Test not recognized if cout << "sometext" << endl; used in TEST body

### ISSUE THREAD

**Issue by marmidr** [offa/NBCndUnit#2] opened 2015-04-29 18:16 UTC
Hi,
today I updated Your plugin to the latest 0.6.0 available in plugin portal.
During porting my test from older tool to CppUTest I found that I should not use cout in TEST body or the test will not be recognized and displayed in Tests Result Window.

TEST(EGOLSCH, SetupEvent)
{
...
    std::cout << "timer events = " << msgque_out.Count() << std::endl;
    CHECK_TRUE(msgque_out.Count() > 30);
}
This is probably because terminal looks like
TEST(EGOLSCH, SetupEvent)timer events = 0

When changed to
std::cout << std::endl << "timer events = " << msgque_out.Count() << std::endl;
everything is Okay.

I'm not sure if this is an issue, I'm writing just for your knowledge :)

**Comment by offa** [comment] 2015-04-29 18:50
> This is probably because terminal looks like
> TEST(EGOLSCH, SetupEvent)timer events = 0

Exactly, the info about the testcases are extracted from such lines.

At the moment a line like `TEST(<test suite>, <test case>)` is parsed as a testcase. If there's some additional Data, the line is not seen as such. I thought about accepting everything after `)` too, but i'm not sure if this introduces new issues.

**Comment by marmidr** [comment] 2015-04-29 18:54
The following terminal output

TEST(EGOLSCH, SetupEvent)
msgque_in  events = 50
msgque_out events = 5
- 1 ms

results in Warning and test failed.

I know how you parse the output and it may be hard to accomplish a really universal parser.

First issue is my fault. But this one... Sometimes additional diagnostic info on terminal is necessary.

**Comment by offa** [comment] 2015-04-29 19:22
I see, yes, that's an issue.

So the C++ code is something like this:

``` cpp
TEST_GROUP(EGOLSCH) { };

TEST(EGOLSCH, SetupEvent)
{
    std::cout << "\nmsgque_in events = 50\n"
            << "msgque_out events = 5\n";
}
```

And the output 

```
TEST(EGOLSCH, SetupEvent)
msgque_in events = 50
msgque_out events = 5
 - 0 ms
```

The cause is the time part separated from the `TEST(...)` - i'll have a look at it.

**Comment by offa** [comment] 2015-04-29 20:31
@mmidor If have pushed a fix. If you have some time you can download an updated version [here](http://www49.zippyshare.com/v/GZ6BdLl2/file.html) (not signed; includes NBM and file with checksum).

**Comment by marmidr** [comment] 2015-04-29 21:02
Verified - works great :)
Thanks again.

**Comment by offa** [comment] 2015-04-29 21:06
Thanks for testing. :+1:

**Closed as completed by offa** 2015-04-29 21:06 UTC
Labels: bug
